### PR TITLE
chore: Use pre-commit for linters

### PR DESCRIPTION
**Pull request by WillDaSilva**

### CODE REVIEW

**Comment by WillDaSilva** [comment]
Actually, on second thought, maybe we should discourage the installation of linters in the dev deps. We can have them installed and run in isolated virtual environments using `pre-commit`. By having them in `pyproject.toml`, we introduce a host of problems from conflicting dependencies, and duplicate the linter dep information across `pyproject.toml` and `.pre-commit-config.yaml`.

**Comment by WillDaSilva** [comment]
I've enabled https://pre-commit.ci for this repository, and moved `mypy` from the test workflow to pre-commit.

Maybe we'll want to do this for Meltano too. It would greatly reduce the number of dependencies Meltano has. Granted this only affects dev deps, but our dev deps limit the ranges of acceptable deps for the Meltano wheel. The cost is that now to e.g. invoke `flake8` we need to run `pre-commit run --all-files flake8`, rather than `poetry run flake8`.

Thoughts? @edgarrmondragon @pandemicsyn

**Comment by edgarrmondragon** [comment]
> I've enabled [pre-commit.ci](https://pre-commit.ci) for this repository, and moved `mypy` from the test workflow to pre-commit.
> 
> Maybe we'll want to do this for Meltano too. It would greatly reduce the number of dependencies Meltano has. Granted this only affects dev deps, but our dev deps limit the ranges of acceptable deps for the Meltano wheel. The cost is that now to e.g. invoke `flake8` we need to run `pre-commit run --all-files flake8`, rather than `poetry run flake8`.
> 
> Thoughts? @edgarrmondragon @pandemicsyn

@WillDaSilva one thing I don't like about using `mypy` and `flake8` as pre-commit hooks is that it's hard to pin specific versions and automate upgrades of additional dependencies (e.g. `types-requests` and `flake8-annotations`) at the same time, which is something that we get for free with Poetry + dependabot.

**Comment by pandemicsyn** [comment]
I honestly don't have strong opinions either way on this one. Having to adjust editor configs to use specific invocations for linters and formatters is a little annoying but also not a huge deal if y'all think its worth it.

My only ask would be that we make sure that we document this somewhere beyond just inline of the pyproject.toml.  Even if its just a quick update to CONTRIBUTING.md.

**Comment by WillDaSilva** [comment]
> one thing I don't like about using mypy and flake8 as pre-commit hooks is that it's hard to pin specific versions and automate upgrades of additional dependencies (e.g. types-requests and flake8-annotations) at the same time, which is something that we get for free with Poetry + dependabot.

@edgarrmondragon This is true, but that problem already exists now. We don't currently autoupdate the dependencies listed under the `additional_dependencies` keys in `.pre-commit-config.yaml`, so they drift out of sync with what's in `poetry.lock`. I'd rather have one source of truth in `.pre-commit-config.yaml` that doesn't autoupdate than two sources of truth that conflict with each other because only one autoupdates.

**Comment by edgarrmondragon** [comment]
> source

@WillDaSilva sounds good 👍

**Review by edgarrmondragon — APPROVED** [review]

**Review by pandemicsyn — APPROVED** [review]

**Comment by WillDaSilva** [comment]
> My only ask would be that we make sure that we document this somewhere beyond just inline of the pyproject.toml. Even if its just a quick update to CONTRIBUTING.md.

Note to self: do this before merging.

**Pull request merged**
